### ISSUE TITLE
black screen, no response after flash (pio on win64) 

### ISSUE THREAD

**Issue by theycallmevirgo** [linuxthor/My-TTGO-Watch#4] opened 2021-09-22 05:18 UTC
upload from pio successful; monitor returns

rst:0x10 (RTCWDT_RTC_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:QIO, clock div:1
load:0x3fff0018,len:4
load:0xffffffff,len:-1
ets Jul 29 2019 12:21:46

**Comment by linguine2552** [comment] 2021-09-25 12:36
I was able to reproduce the bug, looks like linuxthor is working on this project some more. I have an earlier fork that compiles and boots correctly, I'll upload it to my page in case you want it.

**Comment by theycallmevirgo** [comment] 2021-09-30 08:40
> I was able to reproduce the bug, looks like linuxthor is working on this project some more. I have an earlier fork that compiles and boots correctly, I'll upload it to my page in case you want it.

Yes please :).

**Comment by linuxthor** [comment] 2022-05-06 11:53
This should be fixed per the latest version

**Closed as completed by linuxthor** 2022-05-06 11:53 UTC
